function [feResults,reResults,loglike] = bootstrap(m,pv)
% For most datasets, the residuals of a linear mixed model are unlikely to
% be normally distributed. This means the assumptions of the LME are
% violated. In practice, however, this does not affect the fixed effect
% estimates greatly:
% See  Schielzeth, H. et al. Robustness of linear mixed-effects models to violations of
% distributional assumptions. Methods Ecol. Evol. 11, 1141–1152 (2020).
%
% This function provides two methods ('mode') to assess the
% robustness of the fixed effects.
%
% *** Bootstrap resampling subjects.('RESAMPLE' mode) ***
% This mode resamples the data (with replacement) at the subject level
% (assuming that the subject is included as a grouping variable).
%
% In each bootstrap set, we take the data from a random subset of the subjects
% to create a resampled data set with the same number of data rows and
% subjects. Each of these subjects is assigned a new unique name
% (otherwise the number of random effects could change in each iteration)
% then the LME is fit using the same settings as the original model (m).
%
% This mode provides information on the robustness of the original LME. In
% principle the fe output could be used to put bootstrap confidence
% intervals on the original estimates.
%
% *** Non-normality and heteroscedasiticity ***
%  Because LME residuals typically violate the normality and
%  heteroscedasitcity assumptions, one might be concerned that this causes
%  type I or type II errors. This function uses Monte Carlo simulations to
%  assess that risk.
%
% 'Type-I'  mode
%  Here we simulate responses from a model in which the fixed effects are
%  all set to zero. This simulates the null hypothesis.
%
%  'TYPE-II' mode
%  In this mode, we assume that the fitted fixed and random effects in the
%  model are the true parameters and generate datasets based on these parameters.
%
% For either mode (Type-I or Type-II), we model the distribution of the
% residuals of the original model (m) using a non-parametric, epachnikov kernel density
% method (see 'kernel' option in fitdist).  This esatimation can be done
% once for all response values (i.e. assuming homoscedasticity).
% By specifying a number larger than 1 for the 'nrHeteroBins' parameter, this function will divide the
% response data into that many bins (with an approximately equal number of
% sample) and estimate a noise distribution for each bin. The noise for the pseudo-response
% is then generated according to the bin that contains that response.
% In other words, this simulates the heteroscedasiticy found in the data and thereby
% assess whether this violation of the LME assumptions could affect the outcome.
%
% For each simulated data set we add noise from these probability
% distribution that mimic the original residuals, and then estimate the LM
% using the same methods as the original model.
%
% In the type-II mode this asks whether the LME analysis would find the correct
% linear model if the responses were generated by y=X*beta +noise where
% beta are the estimated fixed and random effects, and noise is the
% estimated (non-normal, heteroscedastic) distribution of residuals. If the fixedEffects
% returned by this mode are tightly clustered around the estimated fixed
% effects then we can conclude that the non-normal residuals did not affect
% the estimation greatly. The pTypeII output quantifies the probability of
% concluding that there was no significant effect (per fixed effect). I.e.,
% the type-II error. A pTypeII of NaN means that the effect was not
% significant in the original model.
%
% Note that if you pick a large number of bins to
% model heteroscedasticity, the estimate of the noise in each bin will be worse (fewer
% samples). It is probably best to first inspect the residuals
% (plotResiduals(m,'fitted') and based on that plot determine how many
%  bins are needed to divide the residuals into groups with different
%  distributions. With 'graph' set to true, the last subplot shows the
%  actual residuals in each bin (bar histogram) , plus the kernel estimate (line).
% If these fits look bad (or if all look similar) then you probably have
% too many heteroBins.
%
%%%%%%%%
% INPUT
% m - The  (generalized) linear mixed model
% 'subjectVariable' - Specify which variable should be resampled. ['subject']
% 'nrMonteCarlo' - Number of sets to simulate [100]
% 'nrWorkers' - How many parallel workers to use [0]
% 'graph' - Show an graphical output [false]
% 'mode' - 'RESAMPLE', 'TYPE-II', 'TYPE-I'
% 'alpha' - Significance level for confidence intervals [0.05]
%  'nrHeteroBins' - Number of bins used to simulate heteroscedasticity [1].
% 'exclude' -  A function that takes a data table as input and returns a logical
%               with rows that should be excluded from the model.
%               For instance with a table that has a "response" columnd, the
%               following function would remove outliers from each simulated set
%               @(T) ( isoutlier(T.response))
%               Note: if the original model excluded certain rows of the
%               data table, then those will automatically be excluded from
%               resampling (RESAMPLE mode) or model prediction (type-I/II
%               mode). This exclude function is called after generating
%               the simulated data table and defines additional excludes.
%
% 'null'   -  A string vector with the names of the fixed effects that should be set
%           to zero under the null hypothesis. By default all fixed effects are assumed to be null,
%           but to null = ["x" "y"] will investigate a null model with x
%           and y FE set to zero, while the other FE keep the estimated
%           values.
%
% OUTPUT
% fe  - Struct with
%           .mean - mean of bootstrap sets
%           .std - standard deviation of bootstrap sets
%           .ci  - confidence intervals based on the bootstrap sets.
%           .all  - the full bootstrap set.
%           .significanceMatch shows whether significance reported in the original model
%           matches the outcome of a significance test using the bootstrapped sets (i.e. based on the bootstrap CI)
%           The values in this vector can be -1 (Fixed effects with non-significant values in the original model)
%           1 (FE that are significant according to the original model estimate as well as the bootstrap
%           estimate) or 0 (significant FE that are
%           non-significant according to the bootstrap estimate)
%           The idea here is that one would only draw conclusions about the
%           FE that are significant in the original model, and therefore we
%           only have to flag (with 0) those for which the boostrap estimates
%           does not agree (suggesting that the non-normality of the noise
%           affects the estimate too much).
%
% randomEffects - Struct with mean, stdev, and confidence interval for the
%                   random effects. The .all field contains the full bootstrap set.
%
% loglike  - The log likelihood for each boostrap set.
% BK -  Nov 2022.

arguments
    m (1,1)   % The original LME
    pv.subjectVariable (1,:) string  = "subject" % Indicate which (grouping) variable should be used for resampling
    pv.nrMonteCarlo (1,1) double  = 100 % Number simulated datasets.
    pv.nrWorkers (1,1) double = 0  % Number of parallel workers (parfor)
    pv.mode (1,1) string {mustBeMember(pv.mode,["RESAMPLE","TYPE-I","TYPE-II"])}= "RESAMPLE"  % Mode
    pv.alpha (1,1) double = 0.05 % Significance level
    pv.graph (1,1) logical = false % Show graphs
    pv.nrHeteroBins (1,1) double {mustBeInteger,mustBePositive} = 1  % Model heteroscedasticity with thus number of bins
    pv.exclude (1,1) function_handle = @(x)([]); % Function that takes the data table as input and returns which rows should be excluded.
    pv.null (1,:) string ="";% For the TYPE-I mode; the names of the fixed effects that should be investigated (Defaults to all with "")
end
%#ok<*PFBNS>   % Suppress broadcasting message.

% Preallocate
nrFixedEffects  = size(m.fixedEffects,1);
nrRandomEffects =  size(m.randomEffects,1);
allFixedEffects    = nan(nrFixedEffects,pv.nrMonteCarlo);
fixedEffectsIsSignificant= nan(nrFixedEffects,pv.nrMonteCarlo);
allRandomEffects   = nan(nrRandomEffects,pv.nrMonteCarlo);
loglike         = nan(1,pv.nrMonteCarlo); % Log likelihood.

% Use a dataqueue to show progress updates
dataQueue = parallel.pool.DataQueue;
hWaithBar = waitbar(0,['Bootstrapping ' m.Formula.char ]);
cntr =0;
nrTotal = pv.nrMonteCarlo;
    function updateWaitBar(~)
        cntr=  cntr+1;
        waitbar(cntr/nrTotal,hWaithBar);
    end
afterEach(dataQueue,@updateWaitBar);

% Initialize variables that may not be needed below but have to be defined
% for parfor to compile. They are overruled per mode below.
responseGroupingIx=[];
noiseDistribution  =[] ;
modelResponse =[];
subjects = "";
nrUHeteroBins = 0;
uHeteroBins = [];
simulatedFe = zeros(1,m.NumCoefficients);
switch pv.mode
    case {"TYPE-I","TYPE-II"}
        if pv.mode =="TYPE-I"
            % Create and simulate a null model.
            [simulatedFe,feName]  = fixedEffects(m);
            if pv.null ~=""
                assert(all(ismember(pv.null,feName{:,:})),'Some null fixed effects do not exist in this model?');
                simulatedFe(ismember(feName{:,:},pv.null)) = 0; % Subset of FE 0
            else
                simulatedFe = zeros(size(simulatedFe)); % All FE zero.
            end
            re = randomEffects(m);
            Z = designMatrix(m,'random');
            X =  designMatrix(m,'fixed');            
            modelResponse = X*simulatedFe + Z*re;
        else
            % Simulate the model as estimated to investigate type-II errors
            modelResponse = predict(m);
        end
        out = isnan(modelResponse) | m.ObservationInfo.Excluded;
        originalDataTable = m.Variables(~out,:);
        modelResponse = modelResponse(~out);
        residual = m.residuals;
        residual = residual(~out);
        % To handle heteroscedasiticity, determine bins with the same number of samples per bin
        bins = prctile(modelResponse,linspace(0,100,pv.nrHeteroBins+1));
        % Associate response with the bin
        [~,~,responseGroupingIx]  = histcounts(modelResponse,bins);
        % Kernel density estimate per bin
        noiseDistribution  = fitdist(residual,'kernel','kernel','epanechnikov','By',responseGroupingIx);
        uHeteroBins = unique(responseGroupingIx);
        nrUHeteroBins = numel(uHeteroBins);
    case "RESAMPLE"
        % Grouping used to resample
        out = m.ObservationInfo.Excluded;
        originalDataTable = m.Variables(~out,:);
        subjects        = originalDataTable(:,pv.subjectVariable);
    otherwise
end
uSubjects       = unique(subjects,"rows");
nrSubjects      = size(uSubjects,1);
dummyVarCoding = lm.dummyVarCoding(m);

parfor (i=1:pv.nrMonteCarlo ,pv.nrWorkers )
    % for i=1:pv.nrMonteCarlo % Use this when debugging
    switch pv.mode
        case "RESAMPLE"
            % Select random subset of subjects with resampling and same total
            % number.
            subjectsToUse = uSubjects{randi(nrSubjects,[nrSubjects 1]),:};
            subjectsSoFar = 0;
            % Now create a new data table from the data for this subject, but
            % assign a new ID to each of the resampled subjects
            setT = table;
            for sub = subjectsToUse'
                subjectsSoFar = subjectsSoFar +1; % Used to generate new IDs
                keep = ismember(subjects{:,:},sub);
                resampledSubject= originalDataTable(keep,:);
                % Assign a new ID to each subject
                resampledSubject.(pv.subjectVariable) = repmat(categorical(subjectsSoFar),[sum(keep) 1]);
                setT = [setT; resampledSubject]; %#ok<AGROW>
            end
        case {"TYPE-I","TYPE-II"}
            % For each set, simulate the response as the (linear) prediction of the
            % estimate plus noise based on the kernel estimate of the
            % residuals.
            setT = originalDataTable;
            for b=1:nrUHeteroBins
                thisGroup = responseGroupingIx==uHeteroBins(b);
                setT.(m.ResponseName)(thisGroup) = modelResponse(thisGroup)+ random(noiseDistribution{b},[sum(thisGroup) 1]);
            end
        otherwise
            % Cannot get here, but without it parfor parsing gets confused
            % about setT.
            setT = [];
            error('???')
    end

    % Use the user-supplied funciton to determine which rows to exclude
    exclude = pv.exclude(setT);
    % Estimate model parameters based on the current set.
    if isa(m,'GeneralizedLinearMixedModel')
        thisM =fitglme(setT,char(m.Formula),'Distribution',m.Distribution,'link',m.Link,'DummyVarCoding',dummyVarCoding,'Exclude',exclude);
    else
        thisM =fitlme(setT,char(m.Formula),'DummyVarCoding',dummyVarCoding,'Exclude',exclude);
    end

    % Store the fixed and random effects
    allFixedEffects(:,i) = thisM.fixedEffects;
    fixedEffectsIsSignificant(:,i) = thisM.Coefficients.pValue < pv.alpha;
    allRandomEffects(:,i) = thisM.randomEffects; % TODO - random slopes
    loglike(i) = thisM.ModelCriterion.LogLikelihood;
    % Update the data queue
    send(dataQueue,i);
end
close(hWaithBar);

%% Summarize.

% Results most relevant for the RESAMPLE mode:
feResults.mean = mean(allFixedEffects,2);
feResults.std = std(allFixedEffects,0,2);
feResults.ci   = [prctile(allFixedEffects',100*pv.alpha/2);prctile(allFixedEffects',100*(1-pv.alpha/2))]';
feResults.all = allFixedEffects;
feResults.mismatch = (feResults.mean-m.fixedEffects)./m.fixedEffects;

% Results for the Type-II mode:
if pv.mode == "TYPE-II"
    % Calculate the fraction of sets with non-significant effects.
    % Put a nan for FE that were not significant in the original model
    isSignificant = m.Coefficients.pValue < pv.alpha;
    feResults.pTypeII = nan(nrFixedEffects,1);
    feResults.pTypeII(isSignificant) = mean(~fixedEffectsIsSignificant(isSignificant,:),2);
    % And the fraction in which the FE flips sign (and is significant).
    feResults.pFlip = nan(nrFixedEffects,1);
    isFlip = (sign(feResults.all).*repmat(sign(m.fixedEffects),[1 pv.nrMonteCarlo])) <0 & fixedEffectsIsSignificant;
    feResults.pFlip(isSignificant) = mean(isFlip(isSignificant),2);
else
    % Not meaningful
    feResults.pTypeII = [];
    feResults.pFlip= [];
end

% Results for the Type-I mode:
% Put a NaN if that FE was not set to zero in the null model
if pv.mode == "TYPE-I"
    keepFe = simulatedFe==0;
    feResults.pTypeI = nan(nrFixedEffects,1);
    feResults.pTypeI(keepFe) = mean(fixedEffectsIsSignificant(keepFe,:),2);
else
    feResults.pTypeI = [];
end
% Random effects
reResults.mean = mean(allRandomEffects,2);
reResults.std = std(allRandomEffects,0,2);
reResults.ci   = [prctile(allRandomEffects',100*pv.alpha/2);prctile(allRandomEffects',100*(1-pv.alpha/2))]';
reResults.all = allRandomEffects;

%% Graphical output
% Plot a histogram of each of the fixed effects plus the log likelihood

if pv.graph
    FE = m.fixedEffects;
    clf;
    layout=  tiledlayout("flow");
    for f=1:nrFixedEffects
        % Show a histogram for each fe
        ax(f) = nexttile;
        histogram(allFixedEffects(f,:),'Normalization','probability');
        hold on
        plot(FE(f)*[1 1],ylim,'k','LineWidth',2);
        legStr = ["Simulated Sets" "Orignal FE"];
        if pv.mode =="TYPE-I"
            plot(simulatedFe(f)*[1 1],ylim,'r','LineWidth',2);
            legStr = [legStr "Null FE"];            %#ok<AGROW>
        end

        plot([0 0],ylim,'k','LineWidth',0.5)
        title (sprintf('%s: %.3G CI [%.3G %.3G]',m.CoefficientNames{f},feResults.mean(f),feResults.ci(f,1),feResults.ci(f,2)) ,"Interpreter","none");
        xlabel 'Coefficient'
        ylabel 'Probability'
        xlim(max(abs(xlim))*[-1 1])
        legend(legStr)
    end

    ax(nrFixedEffects+1) = nexttile;ax(nrFixedEffects+1);
    histogram(loglike,'Normalization','probability')
    hold on
    plot(m.ModelCriterion.LogLikelihood*[1 1],ylim,'k','LineWidth',2);
    title (sprintf('%s: %.3G CI [%.3G %.3G]','Log Likelihood:',mean(loglike,"omitnan"),prctile(loglike,2.5),prctile(loglike,97.5)) ,"Interpreter","none");
    xlabel 'Log Likehood'
    ylabel 'Probability'

    if ismember(pv.mode,["TYPE-I" "TYPE-II"])
        % Show the residuals and how they are fit by the kernel density
        ax(nrFixedEffects+2) =nexttile;
        maxResidual = prctile(abs(m.residuals),97.5);
        nrBins = round(numel(m.residuals)/10);
        x= linspace(-maxResidual,maxResidual,nrBins);
        hold on
        R= m.residuals;
        % Match histogram and density colors. Histogram handle does not
        % conatin the color that was used (only 'auto')
        axColors = ax(nrFixedEffects+2).ColorOrder;
        nrColors = size(axColors,1);
        for b=1:nrUHeteroBins
            thisGroup = responseGroupingIx==uHeteroBins(b);
            h = histogram(R(thisGroup),x,'Normalization','Probability');
            thisColor = axColors(mod(b-1,nrColors)+1,:);
            h.FaceColor = thisColor;
            thisPdf =pdf(noiseDistribution{b},x);
            plot(x,thisPdf./sum(thisPdf),'LineWidth',2,'color',thisColor)
        end
        xlim(maxResidual*[-1 1])
        xlabel 'Residual'
        ylabel 'Probability'
        legend('Residuals','Kernel Density Estimate')
    end
    switch (pv.mode)
        case 'TYPE-I'
            % Show type-I error probability per fixed effect
            str = strjoin(string(m.CoefficientNames)' + ": p=" + string(feResults.pTypeI),' ');
        case 'TYPE-II'
            % Show type-II  error probability per fixed effect
            str = strjoin(string(m.CoefficientNames)' + ": p=" + string(feResults.pTypeII),' ');
        case 'RESAMPLE'
            % Show stdev across samples as a percentage of the mean fixed effect
            str = strjoin(string(m.CoefficientNames)' + ": std =" + string(round(100*feResults.std./abs(feResults.mean))) + "%",' ');
    end
    title(layout,[pv.mode + " analysis" ; str],'Interpreter','none')
end

end

